In [246]:
import os
os.environ["KERAS_BACKEND"] = "plaidml.keras.backend"

from keras.datasets import mnist
from keras.utils import np_utils
from keras import layers
from keras import models
from keras.utils import to_categorical
from keras.layers import Convolution2D, MaxPooling2D, Flatten, Dense

In [247]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train.shape

(60000, 28, 28)

In [248]:
X_train = X_train.reshape((60000, 28, 28, 1))
X_train = X_train.astype('float32') / 255
X_test = X_test.reshape((10000, 28, 28, 1))
X_test = X_test.astype('float32') / 255

In [249]:
X_test.shape

(10000, 28, 28, 1)

In [250]:
y_train = to_categorical(y_train,10)
y_test = to_categorical(y_test,10)


In [251]:
model = models.Sequential()

In [252]:
model.add(layers.Convolution2D(32, (3, 3), activation='relu', input_shape=(28, 28,1)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Flatten())
model.add(layers.Dense(64*7, activation = 'relu'))
model.add(layers.Dense(10, activation='softmax'))

In [253]:
model.compile(optimizer='adam',
loss='categorical_crossentropy',
metrics=['accuracy'])

In [254]:
model.fit(X_train, y_train, epochs=4, batch_size=32)

Epoch 1/4
60000/60000 [==============================] - 22s 363us/step - loss: 0.1160 - acc: 0.9630
Epoch 2/4
60000/60000 [==============================] - 22s 365us/step - loss: 0.0378 - acc: 0.9879
Epoch 3/4
60000/60000 [==============================] - 21s 355us/step - loss: 0.0254 - acc: 0.9918
Epoch 4/4
60000/60000 [==============================] - 21s 358us/step - loss: 0.0169 - acc: 0.9944


In [261]:
print(y_test[0])
answer = np.array([0.,0.,0.,0.,0.,1.,0.,0.,0.,0.])
print(answer)

[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [41]:
from os import path
import pathlib

In [42]:
def saveModel(model, fileName):
    file = pathlib.Path(fileName)
    i = 1
    while file.exists():
        fileName = filename + " " + str(i)
        file = pathlib.Path(filenName)
        i += 1
    model.save(fileName)

In [43]:
test_loss, test_acc = model.evaluate(X_test, y_test)
print(test_loss, test_acc)
fileName = 'MnistModel ' + str(test_acc) + ' accuracy'
saveModel(model, fileName)

10000/10000 [==============================] - 1s 123us/step
0.031157955586910247 0.9898


In [44]:
from keras.models import load_model
model2 = load_model("MnistModel 0.99 accuracy")

In [45]:
test_loss, test_acc = model2.evaluate(X_test, y_test)
print(test_loss, test_acc)

10000/10000 [==============================] - 1s 109us/step
0.031153381192684175 0.99


In [206]:
from keras.preprocessing.image import load_img, save_img, img_to_array

In [281]:
numberImage = load_img("Keras5.jpg")

In [282]:
print(type(numberImage))
print(numberImage.format)
print(numberImage.mode)
print(numberImage.size)


<class 'PIL.JpegImagePlugin.JpegImageFile'>
JPEG
RGB
(28, 28)


In [283]:
numberImage

In [284]:
numberArray = img_to_array(numberImage)

In [285]:
import numpy as np
def rgb2gray(rgb):
    return np.dot(rgb[...,:3], [0.2989, 0.5870, 0.1140])

In [286]:
print(numberImage.size)
print(numberImage.mode)
numberArray = rgb2gray(numberArray)
print(numberImage.size)
print(numberImage.mode)

(28, 28)
RGB
(28, 28)
RGB


In [293]:
answer = np.array([0.,0.,0.,0.,0.,1.,0.,0.,0.,0.])
print(numberArray.shape)
print(numberArray)
#numberArray.reshape(1,28,28,1)

(1, 28, 28, 1)
[[[[0.        ]
   [0.        ]
   [0.01568471]
   [0.        ]
   [0.        ]
   [0.        ]
   [0.00392118]
   [0.        ]
   [0.        ]
   [0.01176353]
   [0.        ]
   [0.01176353]
   [0.        ]
   [0.        ]
   [0.        ]
   [0.00784235]
   [0.        ]
   [0.        ]
   [0.00392118]
   [0.        ]
   [0.01176353]
   [0.        ]
   [0.        ]
   [0.00784235]
   [0.        ]
   [0.        ]
   [0.        ]
   [0.        ]]

  [[0.        ]
   [0.01568471]
   [0.        ]
   [0.01568471]
   [0.00784235]
   [0.        ]
   [0.        ]
   [0.        ]
   [0.        ]
   [0.00392118]
   [0.        ]
   [0.        ]
   [0.01176353]
   [0.00784235]
   [0.        ]
   [0.00392118]
   [0.00784235]
   [0.        ]
   [0.        ]
   [0.        ]
   [0.        ]
   [0.00392118]
   [0.        ]
   [0.        ]
   [0.        ]
   [0.        ]
   [0.        ]
   [0.        ]]

  [[0.00784235]
   [0.00784235]
   [0.01568471]
   [0.        ]
   [0.00392118]
   [0

In [292]:
numberArray = np.expand_dims(numberArray, axis = 3)
#numberArray = np.expand_dims(numberArray, axis = 0)
#numberArray = numberArray.astype('float32') / 255


In [294]:
model.predict(numberArray)

array([[1.6363595e-13, 1.2899742e-11, 1.4597596e-12, 2.5307941e-08,
        6.1652571e-12, 9.9999964e-01, 1.5527719e-12, 9.6119290e-10,
        2.9845966e-13, 3.8185459e-07]], dtype=float32)

In [295]:
result = model.evaluate(numberArray,answer)

ValueError: Error when checking target: expected dense_12 to have shape (10,) but got array with shape (1,)

In [205]:
result[0][0]

1.598728e-13