In [221]:
import pandas as pd 
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
import os

In [222]:
df_train = pd.read_csv("train_wine.csv")
df_test = pd.read_csv("test_wine.csv")
df_train = df_train.drop_duplicates()
df_train.duplicated().value_counts()

False    4355
dtype: int64

In [223]:
# mapping = {'poor': 0,'medium': 1, 'good': 2,  'excellent': 3}
# df_train['class'] = [mapping[item] for item in df_train['class']] 

In [224]:
dummies = pd.get_dummies(df_train['color'], drop_first = True)
df_train = df_train.drop(['color'], axis=1)
df_train['isWhite'] = dummies

df_train = df_train.drop(['condition', 'chlor.class', 'vineyard', 'acidity.variance', 
                          'sulfur.taste', 'acid.sulfur', 'acid.taste', 'id'], axis=1)

dummies = pd.get_dummies(df_test['color'], drop_first = True)
df_test = df_test.drop(['color'], axis=1)
df_test['isWhite'] = dummies

df_test = df_test.drop(['condition', 'chlor.class', 'vineyard', 'acidity.variance', 
                          'sulfur.taste', 'acid.sulfur', 'acid.taste'], axis=1)

df_test_without_id = df_test.drop(['id'], axis=1)


In [225]:
# df_train = df_train.drop_duplicates()
print(df_train.duplicated().value_counts())
print(df_train['class'].value_counts())

False    3796
True      559
dtype: int64
good         2624
medium       1433
poor          165
excellent     133
Name: class, dtype: int64


In [226]:
# df_train.corr()["class"].sort_values()

In [227]:
y = df_train['class']
x = df_train.drop(['class'], axis= 1)
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.1)
mapping = {'poor': 0,'medium': 1, 'good': 2,  'excellent': 3}
y_train = [mapping[item] for item in y_train] 
mapping = {'poor':0 ,'medium':1 , 'good': 2,  'excellent': 3}
y_test = [mapping[item] for item in y_test] 

In [230]:
rfc = RandomForestClassifier(n_estimators=200)
rfc.fit(X_train,y_train)
predictions = rfc.predict(X_test)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test,predictions))


              precision    recall  f1-score   support

           0       0.67      0.11      0.18        19
           1       0.69      0.63      0.66       129
           2       0.79      0.89      0.84       275
           3       1.00      0.23      0.38        13

    accuracy                           0.76       436
   macro avg       0.79      0.46      0.51       436
weighted avg       0.76      0.76      0.74       436

[[  2   8   9   0]
 [  1  81  47   0]
 [  0  29 246   0]
 [  0   0  10   3]]


In [ ]:
mapping = {0:"poor",1:"medium",2:"good",3:"excellent"}
predictions =  [mapping[item] for item in predictions]

In [ ]:
import csv
output = pd.DataFrame({"id": df_test.id, "class": predictions})
output.to_csv('wyniki.csv', index=False, quoting=csv.QUOTE_NONNUMERIC)
print("Your submission was successfully saved!")

In [ ]:
log_reg = LogisticRegression().fit(X_train, y_train)
predictions = log_reg.predict(X_test)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test,predictions))